title: Project Title
description: Description
homepage: http://somedomain.com
show_downloads: true
google_analytics: [Your Google Analytics tracking ID]

permalink: /:categories/:title/
markdown: kramdown

theme_color: hsl(215, 50%, 55%)
menu:
  -
    title: "sam"
    url: "/asdasd"
  -
    title: "somethin"
    url: "/dasdasd"
